use serde::{Deserialize, Serialize};

use floem::keyboard::{KeyCode, ModifiersState};

#[derive(Debug, Deserialize, Serialize)]
pub enum KeyModifier {
	Shift,
	Control,
	Alt,
	Super,
	None,
}

pub fn _modifiersstate_to_keymodifier(
	modifiers_state: ModifiersState,
) -> KeyModifier {
	match modifiers_state {
		ModifiersState::SHIFT => KeyModifier::Shift,
		ModifiersState::CONTROL => KeyModifier::Control,
		ModifiersState::ALT => KeyModifier::Alt,
		ModifiersState::SUPER => KeyModifier::Super,
		_ => KeyModifier::None,
	}
}

pub fn _keymodifier_to_modifiersstate(
	key_modifier: KeyModifier,
) -> ModifiersState {
	match key_modifier {
		KeyModifier::Shift => ModifiersState::SHIFT,
		KeyModifier::Control => ModifiersState::CONTROL,
		KeyModifier::Alt => ModifiersState::ALT,
		KeyModifier::Super => ModifiersState::SUPER,
		KeyModifier::None => ModifiersState::empty(),
	}
}

#[derive(Debug, Deserialize, Serialize)]
pub enum Key {
	Backquote,
	Backslash,
	BracketLeft,
	BracketRight,
	Comma,
	Digit0,
	Digit1,
	Digit2,
	Digit3,
	Digit4,
	Digit5,
	Digit6,
	Digit7,
	Digit8,
	Digit9,
	Equal,
	IntlBackslash,
	IntlRo,
	IntlYen,
	KeyA,
	KeyB,
	KeyC,
	KeyD,
	KeyE,
	KeyF,
	KeyG,
	KeyH,
	KeyI,
	KeyJ,
	KeyK,
	KeyL,
	KeyM,
	KeyN,
	KeyO,
	KeyP,
	KeyQ,
	KeyR,
	KeyS,
	KeyT,
	KeyU,
	KeyV,
	KeyW,
	KeyX,
	KeyY,
	KeyZ,
	Minus,
	Period,
	Quote,
	Semicolon,
	Slash,
	AltLeft,
	AltRight,
	Backspace,
	CapsLock,
	ContextMenu,
	ControlLeft,
	ControlRight,
	Enter,
	SuperLeft,
	SuperRight,
	ShiftLeft,
	ShiftRight,
	Space,
	Tab,
	Convert,
	KanaMode,
	Lang1,
	Lang2,
	Lang3,
	Lang4,
	Lang5,
	NonConvert,
	Delete,
	End,
	Help,
	Home,
	Insert,
	PageDown,
	PageUp,
	ArrowDown,
	ArrowLeft,
	ArrowRight,
	ArrowUp,
	NumLock,
	Numpad0,
	Numpad1,
	Numpad2,
	Numpad3,
	Numpad4,
	Numpad5,
	Numpad6,
	Numpad7,
	Numpad8,
	Numpad9,
	NumpadAdd,
	NumpadBackspace,
	NumpadClear,
	NumpadClearEntry,
	NumpadComma,
	NumpadDecimal,
	NumpadDivide,
	NumpadEnter,
	NumpadEqual,
	NumpadHash,
	NumpadMemoryAdd,
	NumpadMemoryClear,
	NumpadMemoryRecall,
	NumpadMemoryStore,
	NumpadMemorySubtract,
	NumpadMultiply,
	NumpadParenLeft,
	NumpadParenRight,
	NumpadStar,
	NumpadSubtract,
	Escape,
	Fn,
	FnLock,
	PrintScreen,
	ScrollLock,
	Pause,
	BrowserBack,
	BrowserFavorites,
	BrowserForward,
	BrowserHome,
	BrowserRefresh,
	BrowserSearch,
	BrowserStop,
	Eject,
	LaunchApp1,
	LaunchApp2,
	LaunchMail,
	MediaPlayPause,
	MediaSelect,
	MediaStop,
	MediaTrackNext,
	MediaTrackPrevious,
	Power,
	Sleep,
	AudioVolumeDown,
	AudioVolumeMute,
	AudioVolumeUp,
	WakeUp,
	Meta,
	Hyper,
	Turbo,
	Abort,
	Resume,
	Suspend,
	Again,
	Copy,
	Cut,
	Find,
	Open,
	Paste,
	Props,
	Select,
	Undo,
	Hiragana,
	Katakana,
	F1,
	F2,
	F3,
	F4,
	F5,
	F6,
	F7,
	F8,
	F9,
	F10,
	F11,
	F12,
	F13,
	F14,
	F15,
	F16,
	F17,
	F18,
	F19,
	F20,
	F21,
	F22,
	F23,
	F24,
	F25,
	F26,
	F27,
	F28,
	F29,
	F30,
	F31,
	F32,
	F33,
	F34,
	F35,
}

pub fn _keycode_to_key(key_code: KeyCode) -> Key {
	match key_code {
		KeyCode::Backquote => Key::Backquote,
		KeyCode::Backslash => Key::Backslash,
		KeyCode::BracketLeft => Key::BracketLeft,
		KeyCode::BracketRight => Key::BracketRight,
		KeyCode::Comma => Key::Comma,
		KeyCode::Digit0 => Key::Digit0,
		KeyCode::Digit1 => Key::Digit1,
		KeyCode::Digit2 => Key::Digit2,
		KeyCode::Digit3 => Key::Digit3,
		KeyCode::Digit4 => Key::Digit4,
		KeyCode::Digit5 => Key::Digit5,
		KeyCode::Digit6 => Key::Digit6,
		KeyCode::Digit7 => Key::Digit7,
		KeyCode::Digit8 => Key::Digit8,
		KeyCode::Digit9 => Key::Digit9,
		KeyCode::Equal => Key::Equal,
		KeyCode::IntlBackslash => Key::IntlBackslash,
		KeyCode::IntlRo => Key::IntlRo,
		KeyCode::IntlYen => Key::IntlYen,
		KeyCode::KeyA => Key::KeyA,
		KeyCode::KeyB => Key::KeyB,
		KeyCode::KeyC => Key::KeyC,
		KeyCode::KeyD => Key::KeyD,
		KeyCode::KeyE => Key::KeyE,
		KeyCode::KeyF => Key::KeyF,
		KeyCode::KeyG => Key::KeyG,
		KeyCode::KeyH => Key::KeyH,
		KeyCode::KeyI => Key::KeyI,
		KeyCode::KeyJ => Key::KeyJ,
		KeyCode::KeyK => Key::KeyK,
		KeyCode::KeyL => Key::KeyL,
		KeyCode::KeyM => Key::KeyM,
		KeyCode::KeyN => Key::KeyN,
		KeyCode::KeyO => Key::KeyO,
		KeyCode::KeyP => Key::KeyP,
		KeyCode::KeyQ => Key::KeyQ,
		KeyCode::KeyR => Key::KeyR,
		KeyCode::KeyS => Key::KeyS,
		KeyCode::KeyT => Key::KeyT,
		KeyCode::KeyU => Key::KeyU,
		KeyCode::KeyV => Key::KeyV,
		KeyCode::KeyW => Key::KeyW,
		KeyCode::KeyX => Key::KeyX,
		KeyCode::KeyY => Key::KeyY,
		KeyCode::KeyZ => Key::KeyZ,
		KeyCode::Minus => Key::Minus,
		KeyCode::Period => Key::Period,
		KeyCode::Quote => Key::Quote,
		KeyCode::Semicolon => Key::Semicolon,
		KeyCode::Slash => Key::Slash,
		KeyCode::AltLeft => Key::AltLeft,
		KeyCode::AltRight => Key::AltRight,
		KeyCode::Backspace => Key::Backspace,
		KeyCode::CapsLock => Key::CapsLock,
		KeyCode::ContextMenu => Key::ContextMenu,
		KeyCode::ControlLeft => Key::ControlLeft,
		KeyCode::ControlRight => Key::ControlRight,
		KeyCode::Enter => Key::Enter,
		KeyCode::SuperLeft => Key::SuperLeft,
		KeyCode::SuperRight => Key::SuperRight,
		KeyCode::ShiftLeft => Key::ShiftLeft,
		KeyCode::ShiftRight => Key::ShiftRight,
		KeyCode::Space => Key::Space,
		KeyCode::Tab => Key::Tab,
		KeyCode::Convert => Key::Convert,
		KeyCode::KanaMode => Key::KanaMode,
		KeyCode::Lang1 => Key::Lang1,
		KeyCode::Lang2 => Key::Lang2,
		KeyCode::Lang3 => Key::Lang3,
		KeyCode::Lang4 => Key::Lang4,
		KeyCode::Lang5 => Key::Lang5,
		KeyCode::NonConvert => Key::NonConvert,
		KeyCode::Delete => Key::Delete,
		KeyCode::End => Key::End,
		KeyCode::Help => Key::Help,
		KeyCode::Home => Key::Home,
		KeyCode::Insert => Key::Insert,
		KeyCode::PageDown => Key::PageDown,
		KeyCode::PageUp => Key::PageUp,
		KeyCode::ArrowDown => Key::ArrowDown,
		KeyCode::ArrowLeft => Key::ArrowLeft,
		KeyCode::ArrowRight => Key::ArrowRight,
		KeyCode::ArrowUp => Key::ArrowUp,
		KeyCode::NumLock => Key::NumLock,
		KeyCode::Numpad0 => Key::Numpad0,
		KeyCode::Numpad1 => Key::Numpad1,
		KeyCode::Numpad2 => Key::Numpad2,
		KeyCode::Numpad3 => Key::Numpad3,
		KeyCode::Numpad4 => Key::Numpad4,
		KeyCode::Numpad5 => Key::Numpad5,
		KeyCode::Numpad6 => Key::Numpad6,
		KeyCode::Numpad7 => Key::Numpad7,
		KeyCode::Numpad8 => Key::Numpad8,
		KeyCode::Numpad9 => Key::Numpad9,
		KeyCode::NumpadAdd => Key::NumpadAdd,
		KeyCode::NumpadBackspace => Key::NumpadBackspace,
		KeyCode::NumpadClear => Key::NumpadClear,
		KeyCode::NumpadClearEntry => Key::NumpadClearEntry,
		KeyCode::NumpadComma => Key::NumpadComma,
		KeyCode::NumpadDecimal => Key::NumpadDecimal,
		KeyCode::NumpadDivide => Key::NumpadDivide,
		KeyCode::NumpadEnter => Key::NumpadEnter,
		KeyCode::NumpadEqual => Key::NumpadEqual,
		KeyCode::NumpadHash => Key::NumpadHash,
		KeyCode::NumpadMemoryAdd => Key::NumpadMemoryAdd,
		KeyCode::NumpadMemoryClear => Key::NumpadMemoryClear,
		KeyCode::NumpadMemoryRecall => Key::NumpadMemoryRecall,
		KeyCode::NumpadMemoryStore => Key::NumpadMemoryStore,
		KeyCode::NumpadMemorySubtract => Key::NumpadMemorySubtract,
		KeyCode::NumpadMultiply => Key::NumpadMultiply,
		KeyCode::NumpadParenLeft => Key::NumpadParenLeft,
		KeyCode::NumpadParenRight => Key::NumpadParenRight,
		KeyCode::NumpadStar => Key::NumpadStar,
		KeyCode::NumpadSubtract => Key::NumpadSubtract,
		KeyCode::Escape => Key::Escape,
		KeyCode::Fn => Key::Fn,
		KeyCode::FnLock => Key::FnLock,
		KeyCode::PrintScreen => Key::PrintScreen,
		KeyCode::ScrollLock => Key::ScrollLock,
		KeyCode::Pause => Key::Pause,
		KeyCode::BrowserBack => Key::BrowserBack,
		KeyCode::BrowserFavorites => Key::BrowserFavorites,
		KeyCode::BrowserForward => Key::BrowserForward,
		KeyCode::BrowserHome => Key::BrowserHome,
		KeyCode::BrowserRefresh => Key::BrowserRefresh,
		KeyCode::BrowserSearch => Key::BrowserSearch,
		KeyCode::BrowserStop => Key::BrowserStop,
		KeyCode::Eject => Key::Eject,
		KeyCode::LaunchApp1 => Key::LaunchApp1,
		KeyCode::LaunchApp2 => Key::LaunchApp2,
		KeyCode::LaunchMail => Key::LaunchMail,
		KeyCode::MediaPlayPause => Key::MediaPlayPause,
		KeyCode::MediaSelect => Key::MediaSelect,
		KeyCode::MediaStop => Key::MediaStop,
		KeyCode::MediaTrackNext => Key::MediaTrackNext,
		KeyCode::MediaTrackPrevious => Key::MediaTrackPrevious,
		KeyCode::Power => Key::Power,
		KeyCode::Sleep => Key::Sleep,
		KeyCode::AudioVolumeDown => Key::AudioVolumeDown,
		KeyCode::AudioVolumeMute => Key::AudioVolumeMute,
		KeyCode::AudioVolumeUp => Key::AudioVolumeUp,
		KeyCode::WakeUp => Key::WakeUp,
		KeyCode::Meta => Key::Meta,
		KeyCode::Hyper => Key::Hyper,
		KeyCode::Turbo => Key::Turbo,
		KeyCode::Abort => Key::Abort,
		KeyCode::Resume => Key::Resume,
		KeyCode::Suspend => Key::Suspend,
		KeyCode::Again => Key::Again,
		KeyCode::Copy => Key::Copy,
		KeyCode::Cut => Key::Cut,
		KeyCode::Find => Key::Find,
		KeyCode::Open => Key::Open,
		KeyCode::Paste => Key::Paste,
		KeyCode::Props => Key::Props,
		KeyCode::Select => Key::Select,
		KeyCode::Undo => Key::Undo,
		KeyCode::Hiragana => Key::Hiragana,
		KeyCode::Katakana => Key::Katakana,
		KeyCode::F1 => Key::F1,
		KeyCode::F2 => Key::F2,
		KeyCode::F3 => Key::F3,
		KeyCode::F4 => Key::F4,
		KeyCode::F5 => Key::F5,
		KeyCode::F6 => Key::F6,
		KeyCode::F7 => Key::F7,
		KeyCode::F8 => Key::F8,
		KeyCode::F9 => Key::F9,
		KeyCode::F10 => Key::F10,
		KeyCode::F11 => Key::F11,
		KeyCode::F12 => Key::F12,
		KeyCode::F13 => Key::F13,
		KeyCode::F14 => Key::F14,
		KeyCode::F15 => Key::F15,
		KeyCode::F16 => Key::F16,
		KeyCode::F17 => Key::F17,
		KeyCode::F18 => Key::F18,
		KeyCode::F19 => Key::F19,
		KeyCode::F20 => Key::F20,
		KeyCode::F21 => Key::F21,
		KeyCode::F22 => Key::F22,
		KeyCode::F23 => Key::F23,
		KeyCode::F24 => Key::F24,
		KeyCode::F25 => Key::F25,
		KeyCode::F26 => Key::F26,
		KeyCode::F27 => Key::F27,
		KeyCode::F28 => Key::F28,
		KeyCode::F29 => Key::F29,
		KeyCode::F30 => Key::F30,
		KeyCode::F31 => Key::F31,
		KeyCode::F32 => Key::F32,
		KeyCode::F33 => Key::F33,
		KeyCode::F34 => Key::F34,
		KeyCode::F35 => Key::F35,
		_ => Key::Fn,
	}
}

pub fn _key_to_codekey(key_code: Key) -> KeyCode {
	match key_code {
		Key::Backquote => KeyCode::Backquote,
		Key::Backslash => KeyCode::Backslash,
		Key::BracketLeft => KeyCode::BracketLeft,
		Key::BracketRight => KeyCode::BracketRight,
		Key::Comma => KeyCode::Comma,
		Key::Digit0 => KeyCode::Digit0,
		Key::Digit1 => KeyCode::Digit1,
		Key::Digit2 => KeyCode::Digit2,
		Key::Digit3 => KeyCode::Digit3,
		Key::Digit4 => KeyCode::Digit4,
		Key::Digit5 => KeyCode::Digit5,
		Key::Digit6 => KeyCode::Digit6,
		Key::Digit7 => KeyCode::Digit7,
		Key::Digit8 => KeyCode::Digit8,
		Key::Digit9 => KeyCode::Digit9,
		Key::Equal => KeyCode::Equal,
		Key::IntlBackslash => KeyCode::IntlBackslash,
		Key::IntlRo => KeyCode::IntlRo,
		Key::IntlYen => KeyCode::IntlYen,
		Key::KeyA => KeyCode::KeyA,
		Key::KeyB => KeyCode::KeyB,
		Key::KeyC => KeyCode::KeyC,
		Key::KeyD => KeyCode::KeyD,
		Key::KeyE => KeyCode::KeyE,
		Key::KeyF => KeyCode::KeyF,
		Key::KeyG => KeyCode::KeyG,
		Key::KeyH => KeyCode::KeyH,
		Key::KeyI => KeyCode::KeyI,
		Key::KeyJ => KeyCode::KeyJ,
		Key::KeyK => KeyCode::KeyK,
		Key::KeyL => KeyCode::KeyL,
		Key::KeyM => KeyCode::KeyM,
		Key::KeyN => KeyCode::KeyN,
		Key::KeyO => KeyCode::KeyO,
		Key::KeyP => KeyCode::KeyP,
		Key::KeyQ => KeyCode::KeyQ,
		Key::KeyR => KeyCode::KeyR,
		Key::KeyS => KeyCode::KeyS,
		Key::KeyT => KeyCode::KeyT,
		Key::KeyU => KeyCode::KeyU,
		Key::KeyV => KeyCode::KeyV,
		Key::KeyW => KeyCode::KeyW,
		Key::KeyX => KeyCode::KeyX,
		Key::KeyY => KeyCode::KeyY,
		Key::KeyZ => KeyCode::KeyZ,
		Key::Minus => KeyCode::Minus,
		Key::Period => KeyCode::Period,
		Key::Quote => KeyCode::Quote,
		Key::Semicolon => KeyCode::Semicolon,
		Key::Slash => KeyCode::Slash,
		Key::AltLeft => KeyCode::AltLeft,
		Key::AltRight => KeyCode::AltRight,
		Key::Backspace => KeyCode::Backspace,
		Key::CapsLock => KeyCode::CapsLock,
		Key::ContextMenu => KeyCode::ContextMenu,
		Key::ControlLeft => KeyCode::ControlLeft,
		Key::ControlRight => KeyCode::ControlRight,
		Key::Enter => KeyCode::Enter,
		Key::SuperLeft => KeyCode::SuperLeft,
		Key::SuperRight => KeyCode::SuperRight,
		Key::ShiftLeft => KeyCode::ShiftLeft,
		Key::ShiftRight => KeyCode::ShiftRight,
		Key::Space => KeyCode::Space,
		Key::Tab => KeyCode::Tab,
		Key::Convert => KeyCode::Convert,
		Key::KanaMode => KeyCode::KanaMode,
		Key::Lang1 => KeyCode::Lang1,
		Key::Lang2 => KeyCode::Lang2,
		Key::Lang3 => KeyCode::Lang3,
		Key::Lang4 => KeyCode::Lang4,
		Key::Lang5 => KeyCode::Lang5,
		Key::NonConvert => KeyCode::NonConvert,
		Key::Delete => KeyCode::Delete,
		Key::End => KeyCode::End,
		Key::Help => KeyCode::Help,
		Key::Home => KeyCode::Home,
		Key::Insert => KeyCode::Insert,
		Key::PageDown => KeyCode::PageDown,
		Key::PageUp => KeyCode::PageUp,
		Key::ArrowDown => KeyCode::ArrowDown,
		Key::ArrowLeft => KeyCode::ArrowLeft,
		Key::ArrowRight => KeyCode::ArrowRight,
		Key::ArrowUp => KeyCode::ArrowUp,
		Key::NumLock => KeyCode::NumLock,
		Key::Numpad0 => KeyCode::Numpad0,
		Key::Numpad1 => KeyCode::Numpad1,
		Key::Numpad2 => KeyCode::Numpad2,
		Key::Numpad3 => KeyCode::Numpad3,
		Key::Numpad4 => KeyCode::Numpad4,
		Key::Numpad5 => KeyCode::Numpad5,
		Key::Numpad6 => KeyCode::Numpad6,
		Key::Numpad7 => KeyCode::Numpad7,
		Key::Numpad8 => KeyCode::Numpad8,
		Key::Numpad9 => KeyCode::Numpad9,
		Key::NumpadAdd => KeyCode::NumpadAdd,
		Key::NumpadBackspace => KeyCode::NumpadBackspace,
		Key::NumpadClear => KeyCode::NumpadClear,
		Key::NumpadClearEntry => KeyCode::NumpadClearEntry,
		Key::NumpadComma => KeyCode::NumpadComma,
		Key::NumpadDecimal => KeyCode::NumpadDecimal,
		Key::NumpadDivide => KeyCode::NumpadDivide,
		Key::NumpadEnter => KeyCode::NumpadEnter,
		Key::NumpadEqual => KeyCode::NumpadEqual,
		Key::NumpadHash => KeyCode::NumpadHash,
		Key::NumpadMemoryAdd => KeyCode::NumpadMemoryAdd,
		Key::NumpadMemoryClear => KeyCode::NumpadMemoryClear,
		Key::NumpadMemoryRecall => KeyCode::NumpadMemoryRecall,
		Key::NumpadMemoryStore => KeyCode::NumpadMemoryStore,
		Key::NumpadMemorySubtract => KeyCode::NumpadMemorySubtract,
		Key::NumpadMultiply => KeyCode::NumpadMultiply,
		Key::NumpadParenLeft => KeyCode::NumpadParenLeft,
		Key::NumpadParenRight => KeyCode::NumpadParenRight,
		Key::NumpadStar => KeyCode::NumpadStar,
		Key::NumpadSubtract => KeyCode::NumpadSubtract,
		Key::Escape => KeyCode::Escape,
		Key::Fn => KeyCode::Fn,
		Key::FnLock => KeyCode::FnLock,
		Key::PrintScreen => KeyCode::PrintScreen,
		Key::ScrollLock => KeyCode::ScrollLock,
		Key::Pause => KeyCode::Pause,
		Key::BrowserBack => KeyCode::BrowserBack,
		Key::BrowserFavorites => KeyCode::BrowserFavorites,
		Key::BrowserForward => KeyCode::BrowserForward,
		Key::BrowserHome => KeyCode::BrowserHome,
		Key::BrowserRefresh => KeyCode::BrowserRefresh,
		Key::BrowserSearch => KeyCode::BrowserSearch,
		Key::BrowserStop => KeyCode::BrowserStop,
		Key::Eject => KeyCode::Eject,
		Key::LaunchApp1 => KeyCode::LaunchApp1,
		Key::LaunchApp2 => KeyCode::LaunchApp2,
		Key::LaunchMail => KeyCode::LaunchMail,
		Key::MediaPlayPause => KeyCode::MediaPlayPause,
		Key::MediaSelect => KeyCode::MediaSelect,
		Key::MediaStop => KeyCode::MediaStop,
		Key::MediaTrackNext => KeyCode::MediaTrackNext,
		Key::MediaTrackPrevious => KeyCode::MediaTrackPrevious,
		Key::Power => KeyCode::Power,
		Key::Sleep => KeyCode::Sleep,
		Key::AudioVolumeDown => KeyCode::AudioVolumeDown,
		Key::AudioVolumeMute => KeyCode::AudioVolumeMute,
		Key::AudioVolumeUp => KeyCode::AudioVolumeUp,
		Key::WakeUp => KeyCode::WakeUp,
		Key::Meta => KeyCode::Meta,
		Key::Hyper => KeyCode::Hyper,
		Key::Turbo => KeyCode::Turbo,
		Key::Abort => KeyCode::Abort,
		Key::Resume => KeyCode::Resume,
		Key::Suspend => KeyCode::Suspend,
		Key::Again => KeyCode::Again,
		Key::Copy => KeyCode::Copy,
		Key::Cut => KeyCode::Cut,
		Key::Find => KeyCode::Find,
		Key::Open => KeyCode::Open,
		Key::Paste => KeyCode::Paste,
		Key::Props => KeyCode::Props,
		Key::Select => KeyCode::Select,
		Key::Undo => KeyCode::Undo,
		Key::Hiragana => KeyCode::Hiragana,
		Key::Katakana => KeyCode::Katakana,
		Key::F1 => KeyCode::F1,
		Key::F2 => KeyCode::F2,
		Key::F3 => KeyCode::F3,
		Key::F4 => KeyCode::F4,
		Key::F5 => KeyCode::F5,
		Key::F6 => KeyCode::F6,
		Key::F7 => KeyCode::F7,
		Key::F8 => KeyCode::F8,
		Key::F9 => KeyCode::F9,
		Key::F10 => KeyCode::F10,
		Key::F11 => KeyCode::F11,
		Key::F12 => KeyCode::F12,
		Key::F13 => KeyCode::F13,
		Key::F14 => KeyCode::F14,
		Key::F15 => KeyCode::F15,
		Key::F16 => KeyCode::F16,
		Key::F17 => KeyCode::F17,
		Key::F18 => KeyCode::F18,
		Key::F19 => KeyCode::F19,
		Key::F20 => KeyCode::F20,
		Key::F21 => KeyCode::F21,
		Key::F22 => KeyCode::F22,
		Key::F23 => KeyCode::F23,
		Key::F24 => KeyCode::F24,
		Key::F25 => KeyCode::F25,
		Key::F26 => KeyCode::F26,
		Key::F27 => KeyCode::F27,
		Key::F28 => KeyCode::F28,
		Key::F29 => KeyCode::F29,
		Key::F30 => KeyCode::F30,
		Key::F31 => KeyCode::F31,
		Key::F32 => KeyCode::F32,
		Key::F33 => KeyCode::F33,
		Key::F34 => KeyCode::F34,
		Key::F35 => KeyCode::F35,
	}
}
