use serde::{Deserialize, Serialize};

use floem::ui_events::keyboard::{Code, Modifiers};

#[allow(dead_code)]
pub fn is_submit(key: Code) -> bool {
	matches!(key, Code::Enter | Code::NumpadEnter)
}

#[derive(Debug, Deserialize, Serialize, PartialEq, Clone)]
pub enum KeyModifier {
	Shift,
	Control,
	Alt,
	Super,
	None,
}

pub fn modifiersstate_to_keymodifier(
	modifiers_state: Modifiers,
) -> KeyModifier {
	match modifiers_state {
		Modifiers::SHIFT => KeyModifier::Shift,
		Modifiers::CONTROL => KeyModifier::Control,
		Modifiers::ALT => KeyModifier::Alt,
		Modifiers::META => KeyModifier::Super,
		_ => KeyModifier::None,
	}
}

#[derive(Debug, Deserialize, Serialize, PartialEq, Clone)]
pub enum Key {
	Backquote,
	Backslash,
	BracketLeft,
	BracketRight,
	Comma,
	Digit0,
	Digit1,
	Digit2,
	Digit3,
	Digit4,
	Digit5,
	Digit6,
	Digit7,
	Digit8,
	Digit9,
	Equal,
	IntlBackslash,
	IntlRo,
	IntlYen,
	KeyA,
	KeyB,
	KeyC,
	KeyD,
	KeyE,
	KeyF,
	KeyG,
	KeyH,
	KeyI,
	KeyJ,
	KeyK,
	KeyL,
	KeyM,
	KeyN,
	KeyO,
	KeyP,
	KeyQ,
	KeyR,
	KeyS,
	KeyT,
	KeyU,
	KeyV,
	KeyW,
	KeyX,
	KeyY,
	KeyZ,
	Minus,
	Period,
	Quote,
	Semicolon,
	Slash,
	AltLeft,
	AltRight,
	Backspace,
	CapsLock,
	ContextMenu,
	ControlLeft,
	ControlRight,
	Enter,
	SuperLeft,
	SuperRight,
	ShiftLeft,
	ShiftRight,
	Space,
	Tab,
	Convert,
	KanaMode,
	Lang1,
	Lang2,
	Lang3,
	Lang4,
	Lang5,
	NonConvert,
	Delete,
	End,
	Help,
	Home,
	Insert,
	PageDown,
	PageUp,
	ArrowDown,
	ArrowLeft,
	ArrowRight,
	ArrowUp,
	NumLock,
	Numpad0,
	Numpad1,
	Numpad2,
	Numpad3,
	Numpad4,
	Numpad5,
	Numpad6,
	Numpad7,
	Numpad8,
	Numpad9,
	NumpadAdd,
	NumpadBackspace,
	NumpadClear,
	NumpadClearEntry,
	NumpadComma,
	NumpadDecimal,
	NumpadDivide,
	NumpadEnter,
	NumpadEqual,
	NumpadHash,
	NumpadMemoryAdd,
	NumpadMemoryClear,
	NumpadMemoryRecall,
	NumpadMemoryStore,
	NumpadMemorySubtract,
	NumpadMultiply,
	NumpadParenLeft,
	NumpadParenRight,
	NumpadStar,
	NumpadSubtract,
	Escape,
	Fn,
	FnLock,
	PrintScreen,
	ScrollLock,
	Pause,
	BrowserBack,
	BrowserFavorites,
	BrowserForward,
	BrowserHome,
	BrowserRefresh,
	BrowserSearch,
	BrowserStop,
	Eject,
	LaunchApp1,
	LaunchApp2,
	LaunchMail,
	MediaPlayPause,
	MediaSelect,
	MediaStop,
	MediaTrackNext,
	MediaTrackPrevious,
	Power,
	Sleep,
	AudioVolumeDown,
	AudioVolumeMute,
	AudioVolumeUp,
	WakeUp,
	Meta,
	Abort,
	Resume,
	Suspend,
	Again,
	Copy,
	Cut,
	Find,
	Open,
	Paste,
	Props,
	Select,
	Undo,
	Hiragana,
	Katakana,
	F1,
	F2,
	F3,
	F4,
	F5,
	F6,
	F7,
	F8,
	F9,
	F10,
	F11,
	F12,
	F13,
	F14,
	F15,
	F16,
	F17,
	F18,
	F19,
	F20,
	F21,
	F22,
	F23,
	F24,
	F25,
	F26,
	F27,
	F28,
	F29,
	F30,
	F31,
	F32,
	F33,
	F34,
	F35,
}

pub fn code_to_key(code: Code) -> Key {
	match code {
		Code::Backquote => Key::Backquote,
		Code::Backslash => Key::Backslash,
		Code::BracketLeft => Key::BracketLeft,
		Code::BracketRight => Key::BracketRight,
		Code::Comma => Key::Comma,
		Code::Digit0 => Key::Digit0,
		Code::Digit1 => Key::Digit1,
		Code::Digit2 => Key::Digit2,
		Code::Digit3 => Key::Digit3,
		Code::Digit4 => Key::Digit4,
		Code::Digit5 => Key::Digit5,
		Code::Digit6 => Key::Digit6,
		Code::Digit7 => Key::Digit7,
		Code::Digit8 => Key::Digit8,
		Code::Digit9 => Key::Digit9,
		Code::Equal => Key::Equal,
		Code::IntlBackslash => Key::IntlBackslash,
		Code::IntlRo => Key::IntlRo,
		Code::IntlYen => Key::IntlYen,
		Code::KeyA => Key::KeyA,
		Code::KeyB => Key::KeyB,
		Code::KeyC => Key::KeyC,
		Code::KeyD => Key::KeyD,
		Code::KeyE => Key::KeyE,
		Code::KeyF => Key::KeyF,
		Code::KeyG => Key::KeyG,
		Code::KeyH => Key::KeyH,
		Code::KeyI => Key::KeyI,
		Code::KeyJ => Key::KeyJ,
		Code::KeyK => Key::KeyK,
		Code::KeyL => Key::KeyL,
		Code::KeyM => Key::KeyM,
		Code::KeyN => Key::KeyN,
		Code::KeyO => Key::KeyO,
		Code::KeyP => Key::KeyP,
		Code::KeyQ => Key::KeyQ,
		Code::KeyR => Key::KeyR,
		Code::KeyS => Key::KeyS,
		Code::KeyT => Key::KeyT,
		Code::KeyU => Key::KeyU,
		Code::KeyV => Key::KeyV,
		Code::KeyW => Key::KeyW,
		Code::KeyX => Key::KeyX,
		Code::KeyY => Key::KeyY,
		Code::KeyZ => Key::KeyZ,
		Code::Minus => Key::Minus,
		Code::Period => Key::Period,
		Code::Quote => Key::Quote,
		Code::Semicolon => Key::Semicolon,
		Code::Slash => Key::Slash,
		Code::AltLeft => Key::AltLeft,
		Code::AltRight => Key::AltRight,
		Code::Backspace => Key::Backspace,
		Code::CapsLock => Key::CapsLock,
		Code::ContextMenu => Key::ContextMenu,
		Code::ControlLeft => Key::ControlLeft,
		Code::ControlRight => Key::ControlRight,
		Code::Enter => Key::Enter,
		Code::MetaLeft => Key::SuperLeft,
		Code::MetaRight => Key::SuperRight,
		Code::ShiftLeft => Key::ShiftLeft,
		Code::ShiftRight => Key::ShiftRight,
		Code::Space => Key::Space,
		Code::Tab => Key::Tab,
		Code::Convert => Key::Convert,
		Code::KanaMode => Key::KanaMode,
		Code::Lang1 => Key::Lang1,
		Code::Lang2 => Key::Lang2,
		Code::Lang3 => Key::Lang3,
		Code::Lang4 => Key::Lang4,
		Code::Lang5 => Key::Lang5,
		Code::NonConvert => Key::NonConvert,
		Code::Delete => Key::Delete,
		Code::End => Key::End,
		Code::Help => Key::Help,
		Code::Home => Key::Home,
		Code::Insert => Key::Insert,
		Code::PageDown => Key::PageDown,
		Code::PageUp => Key::PageUp,
		Code::ArrowDown => Key::ArrowDown,
		Code::ArrowLeft => Key::ArrowLeft,
		Code::ArrowRight => Key::ArrowRight,
		Code::ArrowUp => Key::ArrowUp,
		Code::NumLock => Key::NumLock,
		Code::Numpad0 => Key::Numpad0,
		Code::Numpad1 => Key::Numpad1,
		Code::Numpad2 => Key::Numpad2,
		Code::Numpad3 => Key::Numpad3,
		Code::Numpad4 => Key::Numpad4,
		Code::Numpad5 => Key::Numpad5,
		Code::Numpad6 => Key::Numpad6,
		Code::Numpad7 => Key::Numpad7,
		Code::Numpad8 => Key::Numpad8,
		Code::Numpad9 => Key::Numpad9,
		Code::NumpadAdd => Key::NumpadAdd,
		Code::NumpadBackspace => Key::NumpadBackspace,
		Code::NumpadClear => Key::NumpadClear,
		Code::NumpadClearEntry => Key::NumpadClearEntry,
		Code::NumpadComma => Key::NumpadComma,
		Code::NumpadDecimal => Key::NumpadDecimal,
		Code::NumpadDivide => Key::NumpadDivide,
		Code::NumpadEnter => Key::NumpadEnter,
		Code::NumpadEqual => Key::NumpadEqual,
		Code::NumpadHash => Key::NumpadHash,
		Code::NumpadMemoryAdd => Key::NumpadMemoryAdd,
		Code::NumpadMemoryClear => Key::NumpadMemoryClear,
		Code::NumpadMemoryRecall => Key::NumpadMemoryRecall,
		Code::NumpadMemoryStore => Key::NumpadMemoryStore,
		Code::NumpadMemorySubtract => Key::NumpadMemorySubtract,
		Code::NumpadMultiply => Key::NumpadMultiply,
		Code::NumpadParenLeft => Key::NumpadParenLeft,
		Code::NumpadParenRight => Key::NumpadParenRight,
		Code::NumpadStar => Key::NumpadStar,
		Code::NumpadSubtract => Key::NumpadSubtract,
		Code::Escape => Key::Escape,
		Code::Fn => Key::Fn,
		Code::FnLock => Key::FnLock,
		Code::PrintScreen => Key::PrintScreen,
		Code::ScrollLock => Key::ScrollLock,
		Code::Pause => Key::Pause,
		Code::BrowserBack => Key::BrowserBack,
		Code::BrowserFavorites => Key::BrowserFavorites,
		Code::BrowserForward => Key::BrowserForward,
		Code::BrowserHome => Key::BrowserHome,
		Code::BrowserRefresh => Key::BrowserRefresh,
		Code::BrowserSearch => Key::BrowserSearch,
		Code::BrowserStop => Key::BrowserStop,
		Code::Eject => Key::Eject,
		Code::LaunchApp1 => Key::LaunchApp1,
		Code::LaunchApp2 => Key::LaunchApp2,
		Code::LaunchMail => Key::LaunchMail,
		Code::MediaPlayPause => Key::MediaPlayPause,
		Code::MediaSelect => Key::MediaSelect,
		Code::MediaStop => Key::MediaStop,
		Code::MediaTrackNext => Key::MediaTrackNext,
		Code::MediaTrackPrevious => Key::MediaTrackPrevious,
		Code::Power => Key::Power,
		Code::Sleep => Key::Sleep,
		Code::AudioVolumeDown => Key::AudioVolumeDown,
		Code::AudioVolumeMute => Key::AudioVolumeMute,
		Code::AudioVolumeUp => Key::AudioVolumeUp,
		Code::WakeUp => Key::WakeUp,
		Code::Abort => Key::Abort,
		Code::Resume => Key::Resume,
		Code::Suspend => Key::Suspend,
		Code::Again => Key::Again,
		Code::Copy => Key::Copy,
		Code::Cut => Key::Cut,
		Code::Find => Key::Find,
		Code::Open => Key::Open,
		Code::Paste => Key::Paste,
		Code::Props => Key::Props,
		Code::Select => Key::Select,
		Code::Undo => Key::Undo,
		Code::Hiragana => Key::Hiragana,
		Code::Katakana => Key::Katakana,
		Code::F1 => Key::F1,
		Code::F2 => Key::F2,
		Code::F3 => Key::F3,
		Code::F4 => Key::F4,
		Code::F5 => Key::F5,
		Code::F6 => Key::F6,
		Code::F7 => Key::F7,
		Code::F8 => Key::F8,
		Code::F9 => Key::F9,
		Code::F10 => Key::F10,
		Code::F11 => Key::F11,
		Code::F12 => Key::F12,
		Code::F13 => Key::F13,
		Code::F14 => Key::F14,
		Code::F15 => Key::F15,
		Code::F16 => Key::F16,
		Code::F17 => Key::F17,
		Code::F18 => Key::F18,
		Code::F19 => Key::F19,
		Code::F20 => Key::F20,
		Code::F21 => Key::F21,
		Code::F22 => Key::F22,
		Code::F23 => Key::F23,
		Code::F24 => Key::F24,
		Code::F25 => Key::F25,
		Code::F26 => Key::F26,
		Code::F27 => Key::F27,
		Code::F28 => Key::F28,
		Code::F29 => Key::F29,
		Code::F30 => Key::F30,
		Code::F31 => Key::F31,
		Code::F32 => Key::F32,
		Code::F33 => Key::F33,
		Code::F34 => Key::F34,
		Code::F35 => Key::F35,
		_ => Key::Fn,
	}
}
